### ISSUE TITLE
Why this depercated?

### ISSUE THREAD

**Issue by zzhao0528** [docker-infra/container_exporter#19]
Hi all:

I have some questions,hope anyone can help me.

I notice that monitor container now use cAdvisor, but i don't konw why cadvisor instead of container_exporter?

If i don't use cAdvisor,is there another way to monitor docker container?

Thanks.

**Comment by xbglowx** [comment]
Hi @ZhenyangZhao,

This is deprecated, since it is not worth duplicating efforts. cAdvisor already does everything container_exporter does plus more.

If you don't want to use cAdvisor, you can continue to use this repo (fork) and make the necessary changes you require or build something else from scratch.

**Comment by zzhao0528** [comment]
@xbglowx Thanks a lot.This really helped me.
