### ISSUE TITLE
[Feature] Docker labels

### ISSUE THREAD

**Issue by MrMMorris** [docker-infra/container_exporter#8]
Now that Docker 1.6 has labels, it would be awesome if this exporter could pick those up. Otherwise, I have no way of differentiating different types of container services as I don't name them (I use Consul SERVICE_NAME env var)

**Comment by discordianfish** [comment]
I saw that @usmanismail forked the exporter and added rancher labels.

@usmanismail: Would you be interested in making your change flexible so it can be used to expose any kind of labels and submit that as a PR?

**Comment by usmanismail** [comment]
I had that in mind but the requirement to register the label set with the Prometheus client ahead of time makes this cumbersome. I don't know what labels containers may have so I have no way to register them ahead of time. 

I asked [about this on the mailing list](https://groups.google.com/forum/#!topic/prometheus-developers/HPl5DYlsMrk) and they suggested having a single metrics with value 1 and then applying all labels to it and then using group_left/group_right modifier to do joins over groups of metrics. That flow is complicated enough that I am sure very few people will find labels useful. 

Circling back, if we can get prometheus client to allow arbitrary labels on new metrics or we can find any other way to communicate potential set of labels ahead of time I would love to pull request that in.

**Comment by discordianfish** [comment]
@usmanismail You don't need to know them in advance, you can also create metrics on the fly by using NewConstMetric like here for example: https://github.com/docker-infra/expvar_exporter/blob/master/main.go#L134

An alternative would be to have some configuration which predefines the labels, that would be probably cleaner since you might have lots of labels for your containers which make little sense in prometheus and blows up the metric index if they change often.
A simple mapping like this should be enough for now:

```
environment=io.rancher.environment.name
service=io.rancher.service.name
component=io.rancher.container.system
```

**Comment by usmanismail** [comment]
Ok, let me take another crack at it.
The conf file approach should work

**Comment by juliusv** [comment]
I agree that allowing to predefine or filter the labels that are propagated from Docker->Prometheus is the best solution. In general, you want to make it possible to avoid attaching labels with too high cardinality (like user IDs or email addresses) to Prometheus metrics, because every unique set of labels for a given metrics will generate a new time series.

**Comment by usmanismail** [comment]
See PR #9 
I wanted to keep it simple so no label name renaming if you tag container as X through docker it shows up as X in Prometheus. 
I added a new command line parameter to the binary instead of using a configuration file because its difficult to generate files to mount in with systems like Rancher and Kubernetes.

**Comment by discordianfish** [comment]
Given that #9 is merged, I'll close this one.

**Comment by MrMMorris** [comment]
:tada: thanks! will try this out ASAP
